language: python
install:
    - pip install numpy
    - pip install matplotlib
    - git clone https://github.com/$TRAVIS_REPO_SLUG.git original
    - rm -rf .test
    - mv original/.test .test
script:
    - .test/run
